version: '3'
services:
  nginx:
    container_name: 'resapi_nginx'
    image: 'nginx:1.14'
    ports:
      - '80:80'
    volumes:
      - ./srv:/srv:rw
      - ./docker/nginx/conf/site-default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'laravel'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'false'
      MYSQL_DATABASE: 'root'
    ports:
      - '3308:3306'

  php:
    container_name: 'resapi_php'
    build: './docker/php'
    working_dir: '/srv'
    command: bash -c 'composer install && php-fpm'
    volumes:
      - './srv:/srv'
