# Sử dụng hình ảnh MySQL chính thức làm hình ảnh cơ sở
FROM mysql:latest

# Thiết lập biến môi trường cho MySQL
ENV MYSQL_ROOT_PASSWORD laravel
ENV MYSQL_DATABASE root
ENV MYSQL_USER root
ENV MYSQL_PASSWORD laravel
